# Default Gitry Configuration File

[config]
theme = "nord"  # default theme

[themes]
[themes.nord]
primary = "#88c0d0"
primary_light = "#81a1c1"
text = "#eceff4"
text_dark = "#d8dee9"
muted = "#4c566a"
muted_dark = "#525252"
success = "#a3be8c"
error = "#bf616a"
warning = "#d08770"
diff_add_bg = "#2e3b32"
diff_del_bg = "#3b2e2e"
diff_line_bg = "#3b4252"

[commit]
templates = true

[commit.entries]
name = "feat"
description = "feature - when you add something new"
