name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  aur:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish zengit to AUR
        uses: KSXQB/github-action-aur@v1
        with:
          pkgname: zengit
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
